Minor changes to SDL.Version struct a new class
GeorchW/SharpSDL2 pull request #2
Opened 2022-01-18 06:15 UTC by Blizzardo1

I've upgraded SDL.Version to accept conditional handling such as checking against specific versions of SDL. SdlAvailableAttribute class was created in hopes that it can aide in certain methods of checking whether the requirement is met. For example: SDL.Vulkan_LoadLibrary requires 2.0.6 as this function evidently is only available in that build of SDL. Eventually, I would like to adopt this to every function available to the end-user as a safety net.  I wouldn't commit this just yet as there's not enough to make it worth while.

2023-07-21 06:22 UTC, Blizzardo1 commented
I question this a year later

2023-08-01 06:35 UTC, GeorchW commented
You mean, you're not sure if the changes make sense any more? Or you question the review?

2023-08-02 00:41 UTC, Blizzardo1 commented
I've only questioned it because it was left as a draft and not an actual pull request.  For now, this looks good to me and is ready for review.

2025-05-07 19:11 UTC, Blizzardo1 commented
Hey Georg, Just checking up on this PR.

Thanks

2025-05-15 08:04 UTC, GeorchW requested changes
Ah, turns out I already wrote these comments a long time ago but didn't submit them

2025-05-15 08:04 UTC, GeorchW commented on .vs/VSWorkspaceState.json
> +}
I think this should be added to `.gitignore`, right?

2025-05-15 08:04 UTC, GeorchW commented on SdlAvailableAttribute.cs
> +            SDL.GetVersion(out _actualVersion);
This would cause a lot of calls to `SDL.GetVersion` (one of each use of the attribute). How about making `_expectedVersion` static?

2025-05-15 08:04 UTC, GeorchW commented on SharpSDL2.csproj
> +	</ItemGroup>
Please just move the source code of the attribute to the src folder instead

2025-05-15 08:04 UTC, GeorchW commented on src/SDL/version-revision.cs
> +using System.Runtime.CompilerServices;
These aren't used, right?

2025-05-15 08:04 UTC, GeorchW commented on src/SDL/version-revision.cs
> +        #region Overrides of ValueType
I'm not a fan of `#region`s, honestly, esp. if they contain only a few lines of code

2025-05-15 08:04 UTC, GeorchW commented on src/SDL/vulkan.cs
> +            if (sdl != null && !sdl.Equals()) return -1;
Yeah, the syntax for attributes is a little ugly. I'd write something like 

```csharp
var sdl = typeof(Whatever)
    .GetMethod(nameof(Something))
    .GetAttribute<SdlAvailableAttribute>();
if(sdl?.Equal() != true) // whatever
```

But I'd also just throw an exception instead of returning `-1` here. I believe it is more intuitive to get the exception here instead of getting a MethodNotFoundException or similar

2025-05-15 08:04 UTC, GeorchW commented on src/TTF/Font.cs
> +
?

2025-05-15 19:27 UTC, Blizzardo1 commented on .vs/VSWorkspaceState.json
> +}
Yes, I believe so, don't know why it isn't.

2025-05-15 19:39 UTC, Blizzardo1 commented on SdlAvailableAttribute.cs
> +            SDL.GetVersion(out _actualVersion);
I don't see this file anymore, Should I re-include it?

2025-05-15 19:40 UTC, Blizzardo1 commented on src/SDL/version-revision.cs
> +using System.Runtime.CompilerServices;
This should be fine now as I checked my latest pull and there's no additional using statements.

2025-05-15 19:41 UTC, Blizzardo1 commented on src/SDL/vulkan.cs
> +            if (sdl != null && !sdl.Equals()) return -1;
Yeah this also was removed. Let me know if you would like it reimplemented.

2025-05-15 19:41 UTC, Blizzardo1 commented on src/TTF/Font.cs
> +
This was probably just a fling.

2025-05-15 19:42 UTC, Blizzardo1 commented
What I can do for this one is resubmit the PR if necessary. It can be closed.

2025-05-15 19:42 UTC, closed without merging